name: CI Pipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup pnpm FIRST - reads version from package.json
      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      # Setup Node.js AFTER pnpm (without cache parameter)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Verify pnpm setup
        run: |
          echo "pnpm version: $(pnpm -v)"
          echo "Node version: $(node -v)"

      - name: Install dependencies (workspace)
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm -w lint

      - name: Type check
        run: pnpm -w typecheck

      - name: Test engine with coverage
        run: pnpm -F @poreitsid/engine test -- --coverage

      # Build everything so sim has dist/cli.js available
      - name: Build all packages
        run: pnpm -w build

      # (Optional) make sure the sim specifically is built
      - name: Build sim (explicit)
        run: pnpm -F @poreitsid/sim build

      - name: Run simulation tests
        run: pnpm -F @poreitsid/sim sim -- --games 100

      - name: Security audit (best-effort)
        run: npx osv-scanner -r . || true
        continue-on-error: true

      - name: Upload simulation reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: sim-reports
          path: packages/sim/reports/**
          if-no-files-found: ignore
          retention-days: 30

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: packages/engine/coverage/**
          if-no-files-found: ignore
          retention-days: 30