name: Deploy to Vercel
on:
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'packages/**'
      - 'pnpm-lock.yaml'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preflight (check required secrets)
        run: |
          [ -n "$VERCEL_TOKEN" ] || { echo "❌ VERCEL_TOKEN missing"; exit 1; }
          [ -n "$VERCEL_ORG_ID" ] || { echo "❌ VERCEL_ORG_ID missing"; exit 1; }
          [ -n "$VERCEL_PROJECT_ID" ] || { echo "❌ VERCEL_PROJECT_ID missing"; exit 1; }
          echo "✅ All required secrets are present."

      # Setup pnpm - let it read version from package.json
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Verify pnpm setup
        run: |
          echo "pnpm version: $(pnpm -v)"
          echo "Node version: $(node -v)"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages (workspace)
        run: pnpm -w build

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Show Vercel CLI version
        run: vercel --version

      - name: Vercel Pull (production)
        run: vercel pull --yes --environment=production --token="$VERCEL_TOKEN"
        working-directory: apps/web

      - name: Vercel Build (with pre-installed deps)
        run: vercel build --prod --token="$VERCEL_TOKEN"
        working-directory: apps/web
        env:
          # Tell Vercel to skip install since we already did it
          VERCEL_SKIP_INSTALL: true

      - name: Vercel Deploy (production)
        run: vercel deploy --prebuilt --prod --token="$VERCEL_TOKEN"
        working-directory: apps/web

      - name: Deployment Summary
        if: success()
        run: echo "✅ Successfully deployed to Vercel production"